import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parseCssVars, tailwindUtilFor } from './lib/css-tokens.mjs';

// ui-pes's package.json `exports` map only declares ".", so resolving "./package.json" as a
// subpath fails. Resolve the declared "." entry instead and derive the package dir from it.
const entryUrl = await import.meta.resolve('@universe-forma/ui-pes');
const pkgDir = path.dirname(path.dirname(fileURLToPath(entryUrl)));
const version = JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version;
const css = readFileSync(path.join(pkgDir, 'es/theme.css'), 'utf8');
const dts = readFileSync(path.join(pkgDir, 'es/index.d.ts'), 'utf8');

mkdirSync('ds-catalog', { recursive: true });
const vars = parseCssVars(css);
const banner = `<!-- generated by reindex-ds from @universe-forma/ui-pes@${version}. Token values are product-supplied; use the utility, not a hardcoded value. -->\n`;

const tableFor = (cat) => {
  const rows = vars.filter((v) => v.category === cat)
    .map((v) => `| \`--${v.name}\` | ${tailwindUtilFor(v.name) ?? '—'} |`).join('\n');
  return `${banner}# ${cat} tokens (ui-pes ${version})\n\n| Token | Tailwind utility |\n|---|---|\n${rows}\n`;
};

writeFileSync('ds-catalog/color-tokens.md', tableFor('color'));
writeFileSync('ds-catalog/spacing.md', `${tableFor('spacing')}\n${tableFor('radius')}`);
writeFileSync('ds-catalog/typography.md', tableFor('typography'));

const exports = [...dts.matchAll(/export\s+\{([^}]+)\}/g)]
  .flatMap((m) => m[1].split(',').map((s) => s.trim().split(' as ')[0].trim()))
  .filter((n) => n && /^[A-Z]/.test(n));
const componentRows = [...new Set(exports)].map((n) => `| \`${n}\` | \`import { ${n} } from '@universe-forma/ui-pes'\` |`).join('\n');
writeFileSync('ds-catalog/components.md',
  `${banner}# Components (ui-pes ${version})\n\nNever invent a component. If missing, compose from these + tokens and flag it.\n\n| Component | Import |\n|---|---|\n${componentRows}\n`);

console.log(`reindex-ds: wrote ds-catalog for ui-pes@${version} (${vars.length} tokens, ${new Set(exports).size} components)`);
