name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: forma-amd64-ci
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Install dependency
        id: install
        uses: universe-forma/github-actions/build/dependency/node@main
        with:
          node-version: '23.x'
          package-manager: npm
          install-cmd: npm ci
          github_token: ${{ secrets.GH_TOKEN }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@universe-forma'

      - name: Build app
        id: build
        run: npm run build

      - name: Upload app to S3
        id: s3-upload
        uses: universe-forma/github-actions/deploy/frontend/s3@main
        with:
          s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          app_path: build

      - name: Send Slack Notification
        uses: universe-forma/github-actions/notifications/slack@main
        if: always()
        with:
          slack_webhook_url: ${{ secrets.NOTIFICATIONS_SLACK_WEBHOOK }}
          slack_message: |
            *Environment*: 🔒 vibeconcepts.formatech.io (WAF + Okta)
            *Branch*: `main`
            *Trigger*: 🤖 ${{ github.event_name }}
            ${{ job.status == 'cancelled'
            && 'Pipeline was cancelled manually'
            || job.status == 'success'
            && 'App `ui-design-vibe-concepts` has been deployed successfully'
            || 'App `ui-design-vibe-concepts` deploy failed' }}
            *Steps Status*:
            • Install Dependencies: ${{ steps.install.outcome == 'success' && '✅' || '❌' }}
            • Build: ${{ steps.build.outcome == 'success' && '✅' || '❌' }}
            • S3 Upload: ${{ steps.s3-upload.outcome == 'success' && '✅' || '❌' }}
          slack_title: >-
            ${{ job.status == 'cancelled'
            && ':no_entry_sign: Cancelled'
            || job.status == 'success'
            && ':rocket: Success'
            || ':x: Error' }}
          slack_color: >-
            ${{ job.status == 'cancelled'
            && '#808080'
            || job.status == 'success'
            && '#00ff00'
            || '#ff0000' }}
          slack_username: ui-design-vibe-concepts
